server.port=8080

# MySQL Connection (Update 'YOUR_PASSWORD' with your actual MySQL password)
spring.datasource.url=jdbc:mysql://localhost:3306/proconnectdb
spring.datasource.username=root
spring.datasource.password=Denji@1+2

# Hibernate: Automatically creates the 'service_nodes' table for you
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect