# The URL must match the DB name in Workbench: proconnectdb
spring.datasource.url=jdbc:mysql://localhost:3306/proconnectdb
spring.datasource.username=root
# Use the password you used to log into Workbench (if any)
spring.datasource.password=root123

# This tells Spring Boot to automatically update the table structure
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true